services:
  aiapp-be:
    image: valmai/aiapp:1.0.2
    container_name: aiapp-be
    environment:
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      CLIENT_URL: ${CLIENT_URL}
      JWT_SECRET: ${JWT_SECRET}
      MAIL_HOST_PASSWORD: ${MAIL_HOST_PASSWORD}
      MAIL_HOST_PORT: ${MAIL_HOST_PORT}
      PROD_DB_HOST: aiapp-db
      PROD_DB_NAME: ${DB_NAME}
      PROD_DB_PASSWORD: ${DB_PASSWORD}
      PROD_DB_PORT: 5432
      PROD_DB_USERNAME: ${DB_USERNAME}
      SERVER_URL: ${SERVER_URL}
      spring_profiles_active: "prod"
    ports:
      - "8081:8080"
    volumes:
      - /home/valmai/logging/logs:/var/log:rw
    depends_on:
      - aiapp-db
    restart: unless-stopped

  aiapp-db:
    image: postgres:latest
    container_name: aiapp-db-pg
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data:
